<?xml version="1.0" encoding="UTF-8"?><!-- This file was generated by Altova MapForce 2020  YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.  Refer to the Altova MapForce Documentation for further details. http://www.altova.com/mapforce -->
<xsl:stylesheet version="2.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:ns0="http://purl.org/dc/elements/1.1/"
    xmlns:ns1="http://www.vrt.be/mig/viaa"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:fn="http://www.w3.org/2005/xpath-functions"
    xmlns:ns2="urn:ebu:metadata-schema:ebuCore_2012" exclude-result-prefixes="ns0 ns1 xs fn ns2">
    <xsl:output method="xml" encoding="UTF-8" byte-order-mark="no" indent="yes"/>
    <xsl:template match="/">
        <xsl:variable name="var1_metadataUpdatedEvent" as="node()?" select="ns1:metadataUpdatedEvent"/>
        <Sidecar xmlns="https://zeticon.mediahaven.com/metadata/19.2/mhs/"
            xmlns:mh="https://zeticon.mediahaven.com/metadata/19.2/mh/">
            <xsl:attribute name="xsi:schemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance" select="'https://zeticon.mediahaven.com/metadata/19.2/mhs/ file:///C:/Users/Rudolf/Desktop/mhs.xsd'"/>
            <Descriptive>
                <xsl:for-each select="$var1_metadataUpdatedEvent">
                    <mh:Title>
                        <xsl:sequence select="fn:string(ns1:metadata/ns2:title/ns0:title)"/>
                    </mh:Title>
                </xsl:for-each>
                <xsl:for-each select="$var1_metadataUpdatedEvent/ns1:metadata/ns2:description">
                    <mh:Description>
                        <xsl:sequence select="fn:string(ns0:description)"/>
                    </mh:Description>
                </xsl:for-each>
                <xsl:for-each select="$var1_metadataUpdatedEvent">
                    <mh:CreationDate>
                        <xsl:sequence select="()"/>
                    </mh:CreationDate>
                </xsl:for-each>
                <xsl:for-each select="$var1_metadataUpdatedEvent">
                    <mh:RightsOwner>
                        <xsl:sequence select="()"/>
                    </mh:RightsOwner>
                </xsl:for-each>
            </Descriptive>
        </Sidecar>
    </xsl:template>
</xsl:stylesheet>
