apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    tags: "web-app"
  name: "mtd-transformer"
  labels:
    app: "mtd-transformer"
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: "mtd-transformer-${env}"
      namespace: "vrt-intake"
      labels:
        app: "mtd-transformer"
        app.kubernetes.io/component: "mtd-transformer-${env}"
        app.kubernetes.io/instance: "mtd-transformer-${env}"
        app.kubernetes.io/name: "mtd-transformer"
        app.kubernetes.io/part-of: "mtd-transformer"
        app.openshift.io/runtime: "mtd-transformer"
        app.openshift.io/runtime-version: "${env}"
        env: ${env}
    spec:
      ports:
        - protocol: TCP
          port: ${{svc_port}}
          targetPort: ${{svc_port}}
          name: http
      selector:
        app: "mtd-transformer-${env}"
      clusterIP:
      type: ClusterIP
      sessionAffinity: None
    status:
      loadBalancer: {}
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: "*"
      name: "mtd-transformer-${env}"
      namespace: "vrt-intake"
      labels:
        app: "mtd-transformer"
        app.kubernetes.io/component: "mtd-transformer-${env}"
        app.kubernetes.io/instance: "mtd-transformer-${env}"
        app.kubernetes.io/name: "mtd-transformer"
        app.kubernetes.io/part-of: "mtd-transformer"
        app.openshift.io/runtime: "mtd-transformer"
        app.openshift.io/runtime-version: ${env}
        env: ${env}
    spec:
      replicas: 0
      selector:
        matchLabels:
          app: "mtd-transformer-${env}"
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: "mtd-transformer-${env}"
            deploymentconfig: "mtd-transformer-${env}"
            env: ${env}
          annotations:
            openshift.io/generated-by: OpenShiftWebConsole
        spec:
          containers:
            - name: "mtd-transformer-${env}"
              terminationMessagePath: /dev/termination-log
              resources:
                limits:
                  cpu: '${cpu_limit}m'
                  memory: '${memory_limit}Mi'
                requests:
                  cpu: '${cpu_requested}m'
                  memory: '${memory_requested}Mi'
              ports:
                - containerPort: ${{svc_port}}
                  protocol: TCP
              imagePullPolicy: IfNotPresent
              readinessprobe:
                tcpSocket:
                  port: 8080
                initialDelaySeconds: 15
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
                failureThreshold: 3
              terminationMessagePolicy: File
              envFrom:
                - configMapRef:
                    name: "mtd-transformer-${env}"
              image: >-
                image-registry.openshift-image-registry.svc:5000/vrt-intake/mtd-transformer:${env}
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
          maxSurge: 25%
      revisionHistoryLimit: 10
      progressDeadlineSeconds: 600
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: "mtd-transformer-${env}"
      namespace: "vrt-intake"
      labels:
        app: "mtd-transformer"
        app.kubernetes.io/component: "mtd-transformer-${env}"
        app.kubernetes.io/instance: "mtd-transformer-${env}"
        app.kubernetes.io/name: "mtd-transformer"
        app.kubernetes.io/part-of: "mtd-transformer"
        app.openshift.io/runtime: "mtd-transformer"
        app.openshift.io/runtime-version: ${env}
        env: ${env}
    data:
      key: some_value
parameters:
  - name: env
    value: "env"
  - name: "memory_requested"
    value: "128"
  - name: "memory_limit"
    value: "1028"
  - name: "cpu_requested"
    value: "100"
  - name: "cpu_limit"
    value: "300"
  - name: "svc_port"
    value: "8080"